Repository jenkinsci/workflow-multibranch-plugin, pull requests merged in 2021-12, with the labels that each got.

#145 Add missing nullability annotations and replace JSR 305
  src/main/java/org/jenkinsci/plugins/workflow/multibranch/AbstractWorkflowBranchProjectFactory.java
  src/main/java/org/jenkinsci/plugins/workflow/multibranch/AbstractWorkflowMultiBranchProjectFactory.java
  src/main/java/org/jenkinsci/plugins/workflow/multibranch/BranchJobProperty.java
  src/main/java/org/jenkinsci/plugins/workflow/multibranch/DurabilityHintBranchProperty.java
  src/main/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStep.java
  src/main/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyTrackerAction.java
  src/main/java/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStep.java
  src/main/java/org/jenkinsci/plugins/workflow/multibranch/ResolveScmStep.java
  src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinder.java
  src/main/java/org/jenkinsci/plugins/workflow/multibranch/SCMVar.java
  src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactory.java
  src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProject.java
  src/main/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectFactory.java
  src/test/java/org/jenkinsci/plugins/workflow/multibranch/GitDirectorySCMNavigator.java
  src/test/java/org/jenkinsci/plugins/workflow/multibranch/SCMBinderTest.java
  src/test/java/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectTest.java
Labels: maintenance

#148 Bump plugin parent POM from 4.19 to 4.31
  pom.xml
Labels: dependencies

#147 enable cd
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  pom.xml
Labels: internal
