Repository jenkinsci/workflow-multibranch-plugin, pull requests merged in 2024-01, with the labels that each got.

#287 Adapt standard Jenkins icons
  pom.xml
  src/main/resources/org/jenkinsci/plugins/workflow/multibranch/WorkflowBranchProjectFactory/getting-started-links.jelly
  src/main/resources/org/jenkinsci/plugins/workflow/multibranch/WorkflowMultiBranchProjectFactory/getting-started-links.jelly
Labels: enhancement

#288 Forward compatibility with Guice 7
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStep.java
  src/main/java/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStep.java
Labels: dependencies

#289 Fix deprecations, avoid `@Inject`
  src/main/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStep.java
  src/main/java/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStep.java
Labels: chore
